version: '3.7'

services:
  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
  platform:
    build: .
    ports:
      - 8085:5000
    depends_on:
      - db

volumes:
  postgres_data: